@Host = http://localhost:5203

### prueba 1 _ usuario
POST {{Host}}/api/users
Content-Type: application/json

{
  "username": "admin_prueba",
  "email": "admin@beconsult.com",
  "password": "Password123!"
}

### prueba 2 _ login
POST {{Host}}/api/auth/login
Content-Type: application/json

{
  "username": "admin_prueba",
  "password": "Password123!"
}

### prueba 3 _ usuario
POST {{Host}}/api/users
Content-Type: application/json

{
  "username": "sebastian_admin",
  "email": "sebastian@beconsult.com",
  "password": "Password123!"
}